import assert from 'node:assert/strict';import fs from 'node:fs';import {root,MONSTERS} from './bootstrap.mjs';
const {weekKey,eventRate,EVENT_RATES,WORLD_BOSSES,localBossRuns,WEEKLY_QUESTS}=await import(root+'/js/data/events.js');
const {QuestLog}=await import(root+'/js/systems/Quests.js');const {Player}=await import(root+'/js/entities/Player.js');const {MAPS}=await import(root+'/js/data/maps/index.js');const {GameMap}=await import(root+'/js/world/GameMap.js');const {MonsterManager}=await import(root+'/js/systems/MonsterAI.js');const {EventService}=await import(root+'/js/systems/EventService.js');const {ITEMS}=await import(root+'/js/data/items.js');
assert.equal(weekKey(Date.parse('2026-10-11T23:59:59+07:00')),'2026-10-05');assert.equal(weekKey(Date.parse('2026-10-12T00:00:00+07:00')),'2026-10-12');assert.equal(weekKey(Date.parse('2026-01-01T10:00:00+07:00')),'2025-12-29');
const now=Date.parse('2026-10-11T12:00:00+07:00');for(const rate of EVENT_RATES){assert.equal(eventRate({rate,starts_at:new Date(now).toISOString(),ends_at:null},now),rate);assert.equal(eventRate({rate,starts_at:new Date(now-1000).toISOString(),ends_at:new Date(now).toISOString()},now),1);}assert.equal(eventRate({rate:999,starts_at:new Date(now).toISOString()},now),1);
assert.equal(localBossRuns(now).find(b=>b.type==='world_aurex').status,'active');assert.equal(localBossRuns(now+1800000).find(b=>b.type==='world_aurex').status,'waiting');
for(const b of Object.values(WORLD_BOSSES)){
 const map=new GameMap(MAPS[b.map]);assert(!map.isSolidTile(b.tx,b.ty),'blocked world spawn '+b.map);
 const start=[Math.floor(map.def.spawn.x),Math.floor(map.def.spawn.y)],seen=new Set(),q=[start];for(let i=0;i<q.length;i++){const [x,y]=q[i];for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const xx=x+dx,yy=y+dy,k=xx+','+yy;if(!map.isSolidTile(xx,yy)&&!seen.has(k)){seen.add(k);q.push([xx,yy]);}}}assert(seen.has(b.tx+','+b.ty),'unreachable world spawn');
}
for(const w of Object.values(WEEKLY_QUESTS))for(const [it]of w.rewards.items)assert(ITEMS[it]);
let clock=now;const p=new Player(),L=new QuestLog(p);p.baseLevel=70;L.now=()=>clock;
assert(L.accept('w_hunt').ok);for(let i=0;i<150;i++)L.onKill('bloblet');assert.equal(L.status('w_hunt'),'ready');assert(L.turnIn('w_hunt').ok);assert.equal(L.status('w_hunt'),'done');assert(L.turnIn('w_hunt').error);
assert(L.accept('w_explore').ok);L.onMap('beginner_field');L.onMap('whisper_forest');L.onMap('frostveil_peaks');assert.equal(L.status('w_explore'),'ready');assert(L.turnIn('w_explore').ok);
assert(L.accept('w_world').ok);L.onWorldBoss();assert.equal(L.progress('w_world')[0].cur,1);
const save=p.toSave('asteria_town');const p2=new Player();p2.fromSave(save);const L2=new QuestLog(p2);L2.now=()=>clock;assert.equal(L2.progress('w_world')[0].cur,1);assert.equal(L2.status('w_hunt'),'done');
clock=Date.parse('2026-10-12T00:00:00+07:00');assert.equal(L2.status('w_world'),'available');assert(!p2.quests.active.w_world);assert.equal(L2.status('w_hunt'),'available');assert(L2.accept('w_hunt').ok);assert.equal(L2.progress('w_hunt')[0].cur,0);
L2.now=()=>null;assert.equal(L2.status('w_hunt'),'locked');assert(p2.quests.active.w_hunt);L2.onKill('bloblet');assert.equal(L2.progress('w_hunt')[0].cur,0);
clock=now;let logs=[];const map=new GameMap(MAPS.ancient_ruins),mgr=new MonsterManager(map,[]),g={mode:'offline',started:true,slot:1,player:p,map,mobs:mgr,questLog:L,questEvents:()=>{},dirty:false,saveNow:async()=>{},clearTarget(){this.player.target=null;},gfx:{addMonster(){},playRespawn(){},removeActor(){},playHurt(){},floatText(){}},sfx(){},hud:{log:x=>logs.push(x)}};
const svc=new EventService(g);g.events=svc;svc.now=()=>now;await svc.refresh();assert.equal(mgr.list.filter(m=>m.worldRun).length,1);await svc.refresh();assert.equal(mgr.list.filter(m=>m.worldRun).length,1);let boss=mgr.list[0];const x=boss.x,y=boss.y;for(let i=0;i<30;i++)mgr.update(.1,i*.1,p,{onAttack(){}});assert.equal(boss.x,x);assert.equal(boss.y,y);const before=p.zeny;await svc.hit(boss,{amount:600000},false);assert.equal(mgr.list.length,0);assert.equal(p.zeny-before,30000);await svc.refresh();assert.equal(p.zeny-before,30000);assert(p.quests.worldRuns[boss.worldRun]);const p3=new Player();p3.fromSave(p.toSave('ancient_ruins'));assert(p3.quests.worldRuns[boss.worldRun]);
// Ordinary users cannot change GM rates even if UI actions are called directly.
g.mode='online';g.online={eventSnapshot:async()=>({server_time:new Date(now).toISOString(),admin:false,rates:{exp:{rate:40,starts_at:new Date(now-1000).toISOString(),ends_at:null}},runs:[],notices:[]})};await svc.refresh();assert.equal(svc.rate('exp'),40);await assert.rejects(()=>svc.setRate('exp',2,null));svc.receivedAt-=31000;assert.equal(svc.rate('exp'),1);
// Server notices are deduplicated and appear regardless of the player's map.
g.online.eventSnapshot=async()=>({server_time:new Date(now).toISOString(),admin:false,rates:{},runs:[],notices:[{id:1,message:'spawn'}]});await svc.refresh();await svc.refresh();assert.equal(logs.filter(x=>x.includes('spawn')).length,1);
const sql=fs.readFileSync(root+'/supabase/events.sql','utf8');assert(sql.includes('for update'));assert(sql.includes('primary key(run_id,user_id)'));assert(sql.includes('if not public.is_admin()'));assert(sql.includes('revoke all on function public.event_tick()'));assert(sql.includes("interval '200 milliseconds'"));
const results={version:'0.23.0',rates:EVENT_RATES,worldBosses:2,weeklyQuests:3,weekBoundary:'Monday 00:00 Asia/Bangkok',questReset:true,saveReload:true,duplicateWorldCreditBlocked:true,spawnPointsReachable:true,noticeDedup:true,networkFailClosed:true,jsTests:'passed',sqlExecution:false,browserQA:false};fs.writeFileSync(root+'/docs/events-test-results.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));
