import assert from 'node:assert/strict';import fs from 'node:fs';import {root,MONSTERS,THREE,MonsterView,Image} from './bootstrap.mjs';
const {MAPS}=await import(root+'/js/data/maps/index.js');const {GameMap}=await import(root+'/js/world/GameMap.js');const {ITEMS,BASE_ITEMS,RARITY,itemKey}=await import(root+'/js/data/items.js');const {CARDS,cardDrops}=await import(root+'/js/data/cards.js');const {ENDGAME_MONSTERS}=await import(root+'/js/data/endgameMonsters.js');const {ENDGAME_ITEMS}=await import(root+'/js/data/endgameItems.js');const {BOOK,CARD_SETS}=await import(root+'/js/data/collection.js');const {MonsterManager}=await import(root+'/js/systems/MonsterAI.js');const {MONSTER_MODEL_IDS}=await import(root+'/js/render/Monsters.js');const {Player}=await import(root+'/js/entities/Player.js');const {rollDrops}=await import(root+'/js/systems/Loot.js');const {rollAttack}=await import(root+'/js/systems/Combat.js');const {doSocket}=await import(root+'/js/systems/Forge.js');
const results={version:'0.20.0',mapChecks:[],normalMonsters:11,newMVPs:2,newEquipment:53,newMaterials:4,newCards:13,checks:[]};
// Resolve every drop, reward, equipment and card reference, not just new rows.
for(const [id,m]of Object.entries(MONSTERS)){assert(MONSTER_MODEL_IDS.includes(m.model),id+' model');assert(m.hp>0&&m.baseExp>0);for(const [it,p]of m.drops){assert(ITEMS[it],id+' missing drop '+it);assert(p>=0&&p<=1,id+' drop odds');}for(const reward of Object.values(m.mvpReward||{}))assert(ITEMS[reward]);assert(BOOK[id],id+' missing bestiary');assert(cardDrops(id).length===1,id+' card drop');}
assert.equal(Object.keys(CARDS).length,30);assert.equal(new Set(Object.values(CARDS).map(c=>c.rarity)).size,7);assert.equal(new Set(Object.values(ENDGAME_ITEMS).filter(it=>it.slot==='weapon').map(it=>it.rarity)).size,7);
for(const [id,c]of Object.entries(CARDS)){assert(MONSTERS[c.mob]);assert.equal(ITEMS[id].monster,c.mob);assert(RARITY[c.rarity]);assert(fs.existsSync(root+'/assets/monsters/'+c.mob+'.png'));}
results.checks.push('All drop/item/model/card/reward references; seven card and weapon grades');
for(const mapId of ['ancient_ruins','haunted_forest','ember_caldera']){
 const def=MAPS[mapId],map=new GameMap(def),sx=Math.floor(def.spawn.x),sy=Math.floor(def.spawn.y);assert(!map.isSolidTile(sx,sy),mapId+' spawn blocked');
 const reach=new Set([sy*map.w+sx]),queue=[[sx,sy]];for(let q=0;q<queue.length;q++){const [x,y]=queue[q];for(const [dx,dy]of [[1,0],[-1,0],[0,1],[0,-1]]){const xx=x+dx,yy=y+dy,k=yy*map.w+xx;if(map.isSolidTile(xx,yy)||reach.has(k))continue;reach.add(k);queue.push([xx,yy]);}}
 for(const p of def.portals){let ok=false;for(let y=p.y;y<p.y+p.h;y++)for(let x=p.x;x<p.x+p.w;x++)if(reach.has(y*map.w+x))ok=true;assert(ok,mapId+' portal unreachable '+p.to);const dest=new GameMap(MAPS[p.to]);assert(!dest.boxBlocked(p.arrive.x*16-4,p.arrive.y*16-4,p.arrive.x*16+4,p.arrive.y*16+4),mapId+' blocked arrival '+p.to);}
 for(const n of def.npcs||[])assert(reach.has(n.y*map.w+n.x),mapId+' NPC inaccessible '+n.id);
 for(const sp of def.spawns){let free=0,reached=0;for(const [x,y,w,h]of sp.areas)for(let yy=y;yy<y+h;yy++)for(let xx=x;xx<x+w;xx++)if(!map.isSolidTile(xx,yy)){free++;if(reach.has(yy*map.w+xx))reached++;}assert(free>0,sp.mob+' empty spawn');assert(reached===free,sp.mob+' disconnected spawn');}
 const mgr=new MonsterManager(map,def.spawns);assert.equal(mgr.list.length,def.spawns.reduce((n,s)=>n+s.count,0));
 for(let i=0;i<120;i++)mgr.update(1/30,i/30,{x:def.spawn.x*16,y:def.spawn.y*16,dead:false},{});
 results.mapChecks.push({map:mapId,reachableTiles:reach.size,spawned:mgr.list.length,portals:def.portals.length});
}
results.checks.push('Portal round trips, NPC access, all spawn zones connected; AI spawn and movement');
for(const [id,data]of Object.entries(MONSTERS)){const mob={type:id,data,x:0,y:0,angle:0,moving:true,speedFactor:1};const v=new MonsterView(mob);for(let i=0;i<60;i++)v.update(1/30,mob);v.attack();v.slam();v.update(.1,mob);v.hurt();v.update(.1,mob);v.die();v.update(1,mob);v.respawn();v.update(.6,mob);v.root.traverse(o=>{assert([...o.position.toArray(),...o.quaternion.toArray(),...o.scale.toArray()].every(Number.isFinite),id+' bad transform');});v.dispose();}
results.checks.push('Thirty monster models: movement, attack, boss windup, hurt, death, respawn');
for(const [job,weapon]of [['swordsman','sword'],['mage','staff'],['archer','bow'],['acolyte','mace']]){
 const p=new Player();p.jobId=job;p.baseLevel=95;p.jobLevel=90;p.attr={str:70,agi:60,vit:60,int:80,dex:80,luk:25};p.equip.weapon='bloodmoon_'+weapon;p.equip.body='bloodmoon_body';p.recalc();assert(p.derived.maxHp>2000);assert(p.derived.atk[1]>100);const saved=p.toSave('haunted_forest');const p2=new Player();p2.fromSave(saved);assert.equal(p2.equip.weapon,p.equip.weapon);assert.equal(p2.baseLevel,95);
 p.inventory.add('card_nocthar',1);const result=doSocket(p,{where:'equip',slot:'weapon',key:p.equip.weapon},'card_nocthar');assert(!result.error);assert.equal(p.inventory.count('card_nocthar'),0);assert(ITEMS[p.equip.weapon].cards.includes('card_nocthar'));const key=itemKey('bloodmoon_'+weapon,7,['card_nocthar']);assert(ITEMS[key]);assert.equal(ITEMS[key].rarity,'celestial');assert(ITEMS[key].bonus.atk>BASE_ITEMS['bloodmoon_'+weapon].bonus.atk);
}
const old=new Player();old.fromSave({name:'old',baseLevel:70,job:'swordsman',jobLevel:60,equip:{weapon:'flame_blade*5*card_ignarok'},inventory:[['card_bloblet',1]]});assert(ITEMS[old.equip.weapon]);assert.equal(old.baseLevel,70);assert(old.inventory.count('card_bloblet')===1);
const p=new Player();p.baseLevel=98;p.jobId='swordsman';p.baseExp=p.baseNext-1;p.gainExp(2,0);assert.equal(p.baseLevel,99);assert.equal(p.baseNext,Infinity);
assert(CARD_SETS.find(s=>s.id==='mvp').cards.length===5);assert(CARD_SETS.find(s=>s.id==='ancient').cards.length===6);assert(CARD_SETS.find(s=>s.id==='haunted').cards.length===7);
results.checks.push('Four jobs use new equipment; refine/socket keys and legacy saves still resolve; five-MVP album');
assert(MONSTERS.capling.drops.find(([id])=>id==='cutter')[1]===.025);assert(MONSTERS.ignarok.drops.find(([id])=>id==='flame_blade')[1]===.375);assert.deepEqual(rollDrops([['x',0],['y',1],['z',2]],()=>.5),['y','z']);
let state=12345;const rnd=()=>{state=(state*16807)%2147483647;return state/2147483647;};const counts={};for(let i=0;i<200000;i++)for(const id of rollDrops(MONSTERS.bloodmoon_knight.drops,rnd))counts[id]=(counts[id]||0)+1;
for(const rarity of ['common','uncommon','rare','epic','legend','mythic','celestial']){const table=MONSTERS.bloodmoon_knight.drops.filter(([id])=>ITEMS[id].slot==='weapon'&&ITEMS[id].rarity===rarity),expected=table.reduce((s,[,v])=>s+v,0),actual=table.reduce((s,[id])=>s+(counts[id]||0),0)/200000;assert(Math.abs(expected-actual)<.004,rarity+' odds');}
results.dropSimulation={kills:200000,redWeaponDrops:Object.entries(counts).filter(([id])=>id.startsWith('bloodmoon_')&&ITEMS[id].slot==='weapon').reduce((s,[,n])=>s+n,0)};
results.checks.push('Legacy weapon rates ×2.5; 200,000 deterministic loot rolls verify white–red drops');
fs.writeFileSync(root+'/validation-results.json',JSON.stringify(results,null,2));console.log('PASS',JSON.stringify(results));
